version: "3"
networks:
  nginx-go:
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod.nginx.yml
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - nginx-go
  backend:
    build:
      context: server
    networks:
      - nginx-go
