version: "3.7"
networks:
  localnet:
services:
  nginx:
    image: nginx:1.15
    volumes:
      - /home/nginx.prod.conf.template:/etc/nginx/nginx.conf.template
      - /home/release:/usr/share/nginx/html
    depends_on:
      - backend
    env_file: .env
    networks:
      - localnet
    ports:
      - 80:80
    environment:
      - NGINX_SERVER_NAME=$DOMAIN_NAME
    command: /bin/bash -c "envsubst '$$NGINX_SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
  backend:
    env_file: server/.env
    build:
      context: server
    networks:
      - localnet
