version: "3"
networks:
  nginx-go:
services:
  nginx:
    image: nginx:1.15
    ports:
      - 90:80
    volumes:
      - ./client/release:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    # links:
    #   - backend
    networks:
      - nginx-go
  backend:
    build:
      context: server
    networks:
      - nginx-go
  # db:
  #   image: postgres
  #   env_file: .env
  #   volumes:
  #     - db-data:/var/lib/postgresql/db-data

