FROM golang:1.10

ARG app_env
ENV APP_ENV $app_env

COPY . /go/src/github.com/asxcandrew/herd/server
WORKDIR /go/src/github.com/asxcandrew/herd/server

RUN go get -u github.com/golang/dep/...
RUN dep ensure

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.3.0/wait /wait
RUN chmod +x /wait

## Launch the wait tool and then your application
CMD /wait && go run migrations/*.go && go run main.go

EXPOSE 8080
