FROM golang:1.10

ARG app_env
ENV APP_ENV $app_env

COPY . /go/src/github.com/asxcandrew/herd/server
WORKDIR /go/src/github.com/asxcandrew/herd/server

RUN go get -u github.com/golang/dep/...
RUN dep ensure

RUN go get -u github.com/canthefason/go-watcher/...
RUN go install github.com/canthefason/go-watcher/cmd/watcher

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.3.0/wait /wait
RUN chmod +x /wait

## Launch the wait tool and then your application
CMD /wait && go run migrations/*.go && watcher -run github.com/asxcandrew/herd/server

EXPOSE 8000
